language: node_js

node_js:
  - 8

branches:
  only:
    - master

cache: yarn

env:
  global:
  # SLACK
  - secure: "NmuuDtBCByfWwJXvD86VLnxGjPaRwIMKmNQCAt19YiqnMPNSBOYRzLZfG8JBYeZpKKJkkeVk/gtivGsLbWp+Op2gdxk6CI2md/V28/oD0Xx8xlIjUBiE6rArFfDxufjfaln2SLxg7Ozgl5tdLTJqPSHum0C89ChPYwxwOGcH9Tt14jd22PIvj5srVcGMqp1+GLOxcFr1h46+/eXMsfzg6/WnqlIIp0z0fsYTkq7cY9r1CRSshihU06Kw4P+JZiFbyIu/kYAG384nqmK0MM2sOj6SHjgndpsdjBJH1ILUAAVa3xgnPRV0Ll1apc18QW7pW9VtVDBQNg46u0NSfJV/1Ds2y9ZQSu9+5DrnjCorBI0xs5HgxVFVx/UZpwawEe+605qVdhI3oo9QPictCELQaDkbPm6/E430u18dxerMx8izCFH0hu0pXHyf9riOy0NfYbMa2leQQENIGhw5buT0jqm0CUD/BsdFQkgTzochgMjVyjGf8JGltw4tTzPFzbVugaU+bFA1gokERQRrEqCABQGzoScvjQ0Q6vX5jmiUZ893GrEbDnNE3/VPfwQdSS2xKicfHWFd4Iqqza1SfcClq2DQLPgnAmEi9vsuPSOCUPh5hFXWh3nZRp6/sRJ001zDfhpG+NfDAD1ZTaABLoZwCZqnKbA2ER18IyvrE1db9CE="
  # NPM
  - secure: "bTe/f5TtkaqMYJDtKisdkCIZmeM0RBZXfVWRB3aXOjYd9+QIkORv7BVLyCUB4ZIaXh2y385T7qCsNsfYrHNSFiBMwXQwM4oT4/QxvVHKeqLPEeaDekO7SfGkhsY3wIumBobv1KVWnUITO+vPpmyc5RpDPcrmG9SSln8secATp2WGfsqHefWmvKGcN/P7YY2LVquRNtuqAHqZwvGxdWtpc8d8gCWdnyiaft0gPwNJqOoM0UDlAKqbp21GBZ8Tup9Cwp0umsE0S1oBuK64Sw/5rHcYE2ZVoGjrZUwCTUSJxlGmN1bolVfMqxFo/3vRmRMImxL3X3msNC1U80jgHEjK3m8t0g/jSxgQ1DMI+Ax468hLFjwyTY64rBuYJjtOQBMDjGuoxwSA9BXVjcWwrknv4dlygSE9pfZbW2dLkobcHgKi2rsooZ5NPHRkQ3yhhIlZt6sLbUoLD61ntxIU2hn+cWaxYvEzGu1BvCiaKquXK8/Ikk9jLv/Jv1NsEZd0378BE3yHSS7C5RNmlFLMKS1Qs3v6ljO7Ck94XuCi3hU2CvKmMbPqBxlOHrXoGxFntZzkCrvSL1bS5MEYhgycfQVGmhM/gaPgf/s2mShMdWCjtjEzwaczQhvHsrnbXf3g24B3OdugwRLDIXPve+DmVUf52g1/EoxMrwsoiaN9GlTStHU="
  # GITHUB
  - secure: "OwwhJRDaKasrcx1Asjbn0rxPh25h9F7uF2kTcrcAUpzDKgS9OeT0pbNqyx9Z2q2LS4RIvUczHeIH1mmhJKbYY/kF5xhsUBn99H4zrC2UXdzQY5SQDkCL/3RoIOSLNznqKk429MmMbL8tVsaltWKIKg0cjFHAzaGVK3cJRKViwetiOvfuG61kdbtCXuVpp2KQl0Ujg/9ScxDrtekSY4Y/gCIWTAf+pzkfQY+UjSgoHFQz5SqGkHnqTO5om5rCyBgeYg1KILG2Lt61xzwYpicHCUdr30JRw0dpyFfYEiDf76VspBKfsrW6hmqwZgurjFOf/yN84RWxci6RnGz4gZFFNnsm+e+DnYrm6EVB5jNYIRwsGMZon7RZ6ms6ZIY/F1DtBZCC//af5A79gKa7yZShNbD5p4UxM4kDQvAW7CmhpXc0nRbX0f2VhfA2nbdMrS+pgk31MwySlMN+LiPXRVWonbC0CmETsRdQK1SndutHSJ5xP54Ddrw9QWOhb9e0xKSoMHos4En+Y1AnlV9MjJ58Z/cQ/nTnp2wsdyVD1DWz1NziVthnhoIGJnMrIlCPRCNautr1R3AmBk8hLfhhb5LCklPw/ZnRXefRNyiMSBVv06dCjvmQdaVz8wzh3MLOELlOQHd2ukO6RHDu7ublnazNpSKCOKI77nE67gaKKITyB94="

before_install:
  - echo "//registry.npmjs.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - make travis

after_script:
  - tc-builder slack-notify
