"use strict";
var injectable_1 = require('./injectable');
exports.Inject = injectable_1.Inject;
exports.inject = injectable_1.inject;
var directive_1 = require('./directive');
exports.Directive = directive_1.Directive;
var ng_register_1 = require('./ng-register');
exports.ngRegister = ng_register_1["default"];
var mix_1 = require('./mix');
exports.mix = mix_1.mix;
exports.isinstance = mix_1.isinstance;
var loadNgModule_1 = require('./loadNgModule');
exports.loadNgModule = loadNgModule_1["default"];
